CREATE TABLESPACE mid_term
DATAFILE 'mid_term' SIZE 40M
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE USER jalzate 
IDENTIFIED BY jalzate
DEFAULT TABLESPACE mid_term 
QUOTA UNLIMITED ON mid_term;

CREATE ROLE MINI_DBA;

GRANT CREATE ANY TABLE TO MINI_DBA;
GRANT CREATE SEQUENCE TO MINI_DBA;

CREATE ROLE STUDENT;
GRANT CREATE SESSION TO STUDENT;

GRANT MINI_DBA TO jalzate;

-----------------------------------------------------------------------------------------

    CREATE SEQUENCE SECUENCIA1
    START WITH 500
    INCREMENT BY 1
    NOCYCLE;
    
    CREATE SEQUENCE SECUENCIA2
    START WITH 500
    INCREMENT BY 1
    NOCYCLE;


